Repository ishita1818/Something, pull requests merged in 2018-10, with the labels that each got.

#7 Starting with open source
  novice/start.txt
Labels: good first issue

#8 First html file
  novice/hello.html
Labels: good first issue

#10 Added a new simple webpage
  novice/simple-webite.html
Labels: enhancement

#12 saying hi
  novice/nishitahi.txt
Labels: hacktoberfest

#14 matrix_m*n
  novice/trace.py
Labels: good first issue

#15 circulantmatrix
  novice/circulantmatrix.py
Labels: hacktoberfest, intermediate
